var name='HEMANTH REDDY';
var msg=`Welcome  ${name}`;
console.log(msg);
console.log(msg.length);
console.log(msg.toLowerCase());
console.log(msg.toUpperCase());
console.log(msg.charAt(0));
console.log(msg.charAt(1));
console.log(msg.includes('to'));
console.log(msg.endsWith('y'));
console.log(msg.startsWith('W'));
console.log(msg.indexOf('to'));
console.log(msg.replace('HEMANTH REDDY','HEMU'));
console.log(msg.split(' '));
console.log(msg.substr(0,5));
console.log(msg.search('to'));
console.log(msg.trim());
console.log(msg.trim().length);
console.log(msg.slice(0,5));
console.log(msg.slice(-5));
